---
- hosts: all
  become: true
  pre_tasks:

  - name: update repository index   
    tags: mysql,mariadb,ubuntu 
    apt:
      update_cache: yes

- hosts: all
  become: true
  roles:
    - base

- hosts: webservers
  become: true
  roles:
    - webservers

- hosts: databases
  become: true
  roles:
    - databases

- hosts: workstations
  become: true
  roles:
    - workstations
